---
title: "16S_matrix_HBM_tech_reps"
output: html_document
date: "2022-10-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
setwd("/Users/cbrennan/Documents/Knight_Projects/matrix_tubes/notebooks/tech_reps")
```

```{r}
library(tidyverse)
library(cowplot)
library(ggpubr)
library(svglite)
```

```{r}
tech_rep_jaccard <- read_tsv("16_data_tech_reps_jaccard.txt")
tech_rep_rpca <- read_tsv("16_data_tech_reps_rpca.txt")
tech_rep_unifrac <- read_tsv("16S_data_tech_reps_unifrac.txt")
tech_rep_wunifrac <- read_tsv("16S_data_tech_reps_weighted_unifrac.txt")
```

```{r}
tech_rep_jaccard$sample1_extraction_protocol <- factor(tech_rep_jaccard$sample1_extraction_protocol, levels = c("plate-based", "matrix"))
tech_rep_rpca$sample1_extraction_protocol <- factor(tech_rep_rpca$sample1_extraction_protocol, levels = c("plate-based", "matrix"))
tech_rep_unifrac$sample1_extraction_protocol <- factor(tech_rep_unifrac$sample1_extraction_protocol, levels = c("plate-based", "matrix"))
tech_rep_wunifrac$sample1_extraction_protocol <- factor(tech_rep_wunifrac$sample1_extraction_protocol, levels = c("plate-based", "matrix"))
```

```{r}
tech_rep_jaccard
```

```{r}
levels(tech_rep_jaccard$sample1_extraction_protocol) = c("plate-based", "matrix")
levels(tech_rep_rpca$sample1_extraction_protocol) = c("plate-based", "matrix")
levels(tech_rep_unifrac$sample1_extraction_protocol) = c("plate-based", "matrix")
levels(tech_rep_wunifrac$sample1_extraction_protocol) = c("plate-based", "matrix")
```

# Re-order levels of the sample type variable (optional)
## Note: Change the levels to those for your variable
```{r}
tech_rep_jaccard$sample_type2 <- factor(tech_rep_jaccard$sample_type2, levels = c("human_feces", "mouse_feces", "human_saliva_before_brushing", "human_saliva_after_brushing"))
tech_rep_rpca$sample_type2 <- factor(tech_rep_rpca$sample_type2, levels = c("human_feces", "mouse_feces", "human_saliva_before_brushing", "human_saliva_after_brushing"))
tech_rep_unifrac$sample_type2 <- factor(tech_rep_unifrac$sample_type2, levels = c("human_feces", "mouse_feces", "human_saliva_before_brushing", "human_saliva_after_brushing"))
tech_rep_wunifrac$sample_type2 <- factor(tech_rep_wunifrac$sample_type2, levels = c("human_feces", "mouse_feces", "human_saliva_before_brushing", "human_saliva_after_brushing"))
```

# Re-name levels for the sample type variable (optional)
## Note: Change the levels to those for your variable
```{r}
levels(tech_rep_jaccard$sample_type2) <- c("human_feces", "mouse_feces", "saliva_before_brush", "saliva_after_brush")
levels(tech_rep_rpca$sample_type2) <- c("human_feces", "mouse_feces", "saliva_before_brush", "saliva_after_brush")
levels(tech_rep_unifrac$sample_type2) <- c("human_feces", "mouse_feces", "saliva_before_brush", "saliva_after_brush")
levels(tech_rep_wunifrac$sample_type2) <- c("human_feces", "mouse_feces", "saliva_before_brush", "saliva_after_brush")
```

```{r}
tech_rep_jaccard_plate <- filter(tech_rep_jaccard,sample2_extraction_protocol == "plate-based")
tech_rep_jaccard_matrix <- filter(tech_rep_jaccard,sample2_extraction_protocol == "matrix")
tech_rep_jaccard_plate_mouse <- filter(tech_rep_jaccard_plate,sample_type2 == "mouse_feces")
tech_rep_jaccard_matrix_mouse <- filter(tech_rep_jaccard_matrix,sample_type2 == "mouse_feces")

wilcox.test(tech_rep_jaccard_plate_mouse$value, tech_rep_jaccard_matrix_mouse$value)
```

```{r}
tech_rep_rpca_plate <- filter(tech_rep_rpca,sample2_extraction_protocol == "plate-based")
tech_rep_rpca_matrix <- filter(tech_rep_rpca,sample2_extraction_protocol == "matrix")
tech_rep_rpca_plate_mouse <- filter(tech_rep_rpca_plate,sample_type2 == "mouse_feces")
tech_rep_rpca_matrix_mouse <- filter(tech_rep_rpca_matrix,sample_type2 == "mouse_feces")

wilcox.test(tech_rep_rpca_plate_mouse$value, tech_rep_rpca_matrix_mouse$value)
```

```{r}
tech_rep_unifrac_plate <- filter(tech_rep_unifrac,sample2_extraction_protocol == "plate-based")
tech_rep_unifrac_matrix <- filter(tech_rep_unifrac,sample2_extraction_protocol == "matrix")
tech_rep_unifrac_plate_mouse <- filter(tech_rep_unifrac_plate,sample_type2 == "mouse_feces")
tech_rep_unifrac_matrix_mouse <- filter(tech_rep_unifrac_matrix,sample_type2 == "mouse_feces")

wilcox.test(tech_rep_unifrac_plate_mouse$value, tech_rep_unifrac_matrix_mouse$value)
```

```{r}
tech_rep_wunifrac_plate <- filter(tech_rep_wunifrac,sample2_extraction_protocol == "plate-based")
tech_rep_wunifrac_matrix <- filter(tech_rep_wunifrac,sample2_extraction_protocol == "matrix")
tech_rep_wunifrac_plate_mouse <- filter(tech_rep_wunifrac_plate,sample_type2 == "mouse_feces")
tech_rep_wunifrac_matrix_mouse <- filter(tech_rep_wunifrac_matrix,sample_type2 == "mouse_feces")

wilcox.test(tech_rep_wunifrac_plate_mouse$value, tech_rep_wunifrac_matrix_mouse$value)
```

```{r}
tech_rep_jaccard_plate <- filter(tech_rep_jaccard,sample2_extraction_protocol == "plate-based")
tech_rep_jaccard_matrix <- filter(tech_rep_jaccard,sample2_extraction_protocol == "matrix")
tech_rep_jaccard_plate_human <- filter(tech_rep_jaccard_plate,sample_type2 == "human_feces")
tech_rep_jaccard_matrix_human <- filter(tech_rep_jaccard_matrix,sample_type2 == "human_feces")

wilcox.test(tech_rep_jaccard_plate_human$value, tech_rep_jaccard_matrix_human$value)
```

```{r}
tech_rep_rpca_plate <- filter(tech_rep_rpca,sample2_extraction_protocol == "plate-based")
tech_rep_rpca_matrix <- filter(tech_rep_rpca,sample2_extraction_protocol == "matrix")
tech_rep_rpca_plate_human <- filter(tech_rep_rpca_plate,sample_type2 == "human_feces")
tech_rep_rpca_matrix_human <- filter(tech_rep_rpca_matrix,sample_type2 == "human_feces")

wilcox.test(tech_rep_rpca_plate_human$value, tech_rep_rpca_matrix_human$value)
```

```{r}
tech_rep_unifrac_plate <- filter(tech_rep_unifrac,sample2_extraction_protocol == "plate-based")
tech_rep_unifrac_matrix <- filter(tech_rep_unifrac,sample2_extraction_protocol == "matrix")
tech_rep_unifrac_plate_human <- filter(tech_rep_unifrac_plate,sample_type2 == "human_feces")
tech_rep_unifrac_matrix_human <- filter(tech_rep_unifrac_matrix,sample_type2 == "human_feces")

wilcox.test(tech_rep_unifrac_plate_human$value, tech_rep_unifrac_matrix_human$value)
```

```{r}
tech_rep_wunifrac_plate <- filter(tech_rep_wunifrac,sample2_extraction_protocol == "plate-based")
tech_rep_wunifrac_matrix <- filter(tech_rep_wunifrac,sample2_extraction_protocol == "matrix")
tech_rep_wunifrac_plate_human <- filter(tech_rep_wunifrac_plate,sample_type2 == "human_feces")
tech_rep_wunifrac_matrix_human <- filter(tech_rep_wunifrac_matrix,sample_type2 == "human_feces")

wilcox.test(tech_rep_wunifrac_plate_human$value, tech_rep_wunifrac_matrix_human$value)
```

```{r}
tech_rep_jaccard_plate <- filter(tech_rep_jaccard,sample2_extraction_protocol == "plate-based")
tech_rep_jaccard_matrix <- filter(tech_rep_jaccard,sample2_extraction_protocol == "matrix")
tech_rep_jaccard_plate_saliva_before <- filter(tech_rep_jaccard_plate,sample_type2 == "saliva_before_brush")
tech_rep_jaccard_matrix_saliva_before <- filter(tech_rep_jaccard_matrix,sample_type2 == "saliva_before_brush")

wilcox.test(tech_rep_jaccard_plate_saliva_before$value, tech_rep_jaccard_matrix_saliva_before$value)
```

```{r}
tech_rep_rpca_plate <- filter(tech_rep_rpca,sample2_extraction_protocol == "plate-based")
tech_rep_rpca_matrix <- filter(tech_rep_rpca,sample2_extraction_protocol == "matrix")
tech_rep_rpca_plate_saliva_before <- filter(tech_rep_rpca_plate,sample_type2 == "saliva_before_brush")
tech_rep_rpca_matrix_saliva_before <- filter(tech_rep_rpca_matrix,sample_type2 == "saliva_before_brush")

wilcox.test(tech_rep_rpca_plate_saliva_before$value, tech_rep_rpca_matrix_saliva_before$value)
```

```{r}
tech_rep_unifrac_plate <- filter(tech_rep_unifrac,sample2_extraction_protocol == "plate-based")
tech_rep_unifrac_matrix <- filter(tech_rep_unifrac,sample2_extraction_protocol == "matrix")
tech_rep_unifrac_plate_saliva_before <- filter(tech_rep_unifrac_plate,sample_type2 == "saliva_before_brush")
tech_rep_unifrac_matrix_saliva_before <- filter(tech_rep_unifrac_matrix,sample_type2 == "saliva_before_brush")

wilcox.test(tech_rep_unifrac_plate_saliva_before$value, tech_rep_unifrac_matrix_saliva_before$value)
```

```{r}
tech_rep_wunifrac_plate <- filter(tech_rep_wunifrac,sample2_extraction_protocol == "plate-based")
tech_rep_wunifrac_matrix <- filter(tech_rep_wunifrac,sample2_extraction_protocol == "matrix")
tech_rep_wunifrac_plate_saliva_before <- filter(tech_rep_wunifrac_plate,sample_type2 == "saliva_before_brush")
tech_rep_wunifrac_matrix_saliva_before <- filter(tech_rep_wunifrac_matrix,sample_type2 == "saliva_before_brush")

wilcox.test(tech_rep_wunifrac_plate_saliva_before$value, tech_rep_wunifrac_matrix_saliva_before$value)
```


```{r}
tech_rep_jaccard_plate <- filter(tech_rep_jaccard,sample2_extraction_protocol == "plate-based")
tech_rep_jaccard_matrix <- filter(tech_rep_jaccard,sample2_extraction_protocol == "matrix")
tech_rep_jaccard_plate_saliva_after <- filter(tech_rep_jaccard_plate,sample_type2 == "saliva_after_brush")
tech_rep_jaccard_matrix_saliva_after <- filter(tech_rep_jaccard_matrix,sample_type2 == "saliva_after_brush")

wilcox.test(tech_rep_jaccard_plate_saliva_after$value, tech_rep_jaccard_matrix_saliva_after$value)
```

```{r}
tech_rep_rpca_plate <- filter(tech_rep_rpca,sample2_extraction_protocol == "plate-based")
tech_rep_rpca_matrix <- filter(tech_rep_rpca,sample2_extraction_protocol == "matrix")
tech_rep_rpca_plate_saliva_after <- filter(tech_rep_rpca_plate,sample_type2 == "saliva_after_brush")
tech_rep_rpca_matrix_saliva_after <- filter(tech_rep_rpca_matrix,sample_type2 == "saliva_after_brush")

wilcox.test(tech_rep_rpca_plate_saliva_after$value, tech_rep_rpca_matrix_saliva_after$value)
```

```{r}
tech_rep_unifrac_plate <- filter(tech_rep_unifrac,sample2_extraction_protocol == "plate-based")
tech_rep_unifrac_matrix <- filter(tech_rep_unifrac,sample2_extraction_protocol == "matrix")
tech_rep_unifrac_plate_saliva_after <- filter(tech_rep_unifrac_plate,sample_type2 == "saliva_after_brush")
tech_rep_unifrac_matrix_saliva_after <- filter(tech_rep_unifrac_matrix,sample_type2 == "saliva_after_brush")

wilcox.test(tech_rep_unifrac_plate_saliva_after$value, tech_rep_unifrac_matrix_saliva_after$value)
```

```{r}
tech_rep_wunifrac_plate <- filter(tech_rep_wunifrac,sample2_extraction_protocol == "plate-based")
tech_rep_wunifrac_matrix <- filter(tech_rep_wunifrac,sample2_extraction_protocol == "matrix")
tech_rep_wunifrac_plate_saliva_after <- filter(tech_rep_wunifrac_plate,sample_type2 == "saliva_after_brush")
tech_rep_wunifrac_matrix_saliva_after <- filter(tech_rep_wunifrac_matrix,sample_type2 == "saliva_after_brush")

wilcox.test(tech_rep_wunifrac_plate_saliva_after$value, tech_rep_wunifrac_matrix_saliva_after$value)
```

```{r}
data_text_W <- data.frame(jaccard = c("W=156", "W=72","W=36","W=45"), RPCA = c("W=280","W=104","W=53","W=79"), unifrac = c("W=233","W=67","W=31","W=48"), wunifrac = c("W=375","W=148","W=40","W=104"),x = 1.5, y = c(1,1,1,1), sample_type2 =c("human_feces", "mouse_feces" ,"saliva_before_brush", "saliva_after_brush"))
data_text_W$sample_type2 <- factor(data_text_W$sample_type2, levels = c("human_feces", "mouse_feces", "saliva_before_brush", "saliva_after_brush"))
data_text_W
```


```{r}
boxplot_jaccard <- ggplot(tech_rep_jaccard, aes(x = sample1_extraction_protocol, y = value)) +
  facet_wrap(~sample_type2) +
  geom_boxplot(outlier.alpha = 0, aes(fill = sample1_extraction_protocol)) +
  geom_jitter(width = 0.2, size = 0.5) +
  stat_summary(fun = mean, geom = "point", color = "black", fill = "red", shape = 21) +
  stat_compare_means(method = "wilcox.test",paired = F,vjust=2, hjust=-0.2,size =4) +
  ylab("Within sample\nJaccard distance") +
  geom_vline(xintercept = 3.5,
             color = "black",
             size = 0.25) +
  ylim(c(-0.01,1.5)) +
  scale_fill_manual(values = c("blue", "steelblue1")) +
  theme_bw() +
geom_text(data = data_text_W, mapping = aes(x = x, y = y, label = jaccard),
  size =4) +
  theme(axis.title.x = element_blank(),
        legend.position = "none", 
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        text = element_text(size = 16),
        strip.background =element_rect(fill="white"))

boxplot_rpca <- ggplot(tech_rep_rpca, aes(x = sample1_extraction_protocol, y = value)) +
  facet_wrap(~sample_type2,
             ncol = 5) +
  geom_boxplot(outlier.alpha = 0, aes(fill = sample1_extraction_protocol)) +
  geom_jitter(width = 0.2, size = 0.5) +
  stat_compare_means(method = "wilcox.test",paired = F,vjust=2, hjust=0.2,size =4) +
  stat_summary(fun = mean, geom = "point", color = "black", fill = "red", shape = 21) +
  ylab("Within sample\nRobust Aitchison distance") +
  geom_vline(xintercept = 3.5,
             color = "black",
             size = 0.25) +
  ylim(c(-0.01,2)) +
  scale_fill_manual(values = c("blue", "steelblue1")) +
  theme_bw() +
  geom_text(data = data_text_W, mapping = aes(x = x, y = 1.7, label = RPCA),
  size =4) +
  theme(axis.title.x = element_blank(),
        legend.position = "none", 
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        text = element_text(size = 14),
        strip.background =element_rect(fill="white"))

boxplot_unifrac <- ggplot(tech_rep_unifrac, aes(x = sample1_extraction_protocol, y = value)) +
  facet_wrap(~sample_type2) +
  geom_boxplot(outlier.alpha = 0, aes(fill = sample1_extraction_protocol)) +
  geom_jitter(width = 0.2, size = 0.5) +
  stat_summary(fun = mean, geom = "point", color = "black", fill = "red", shape = 21) +
  stat_compare_means(method = "wilcox.test",paired = F,vjust=2, hjust=-0.2,size =4) +
  ylab("Within sample\nunweighted UniFrac distance") +
  geom_vline(xintercept = 3.5,
             color = "black",
             size = 0.25) +
  ylim(c(-0.01,1.5)) +
  scale_fill_manual(values = c("blue", "steelblue1")) +
  theme_bw() +
  geom_text(data = data_text_W, mapping = aes(x = x, y = y, label = unifrac),
  size =4) +
  theme(axis.title.x = element_blank(),
        legend.position = "none", 
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        text = element_text(size = 14),
        strip.background =element_rect(fill="white"))

boxplot_wunifrac <- ggplot(tech_rep_wunifrac, aes(x = sample1_extraction_protocol, y = value)) +
  facet_wrap(~sample_type2) +
  geom_boxplot(outlier.alpha = 0, aes(fill = sample1_extraction_protocol)) +
  geom_jitter(width = 0.2, size = 0.5) +
  stat_compare_means(method = "wilcox.test",paired = F,vjust=2, hjust=-0.2,size =4) +
  stat_summary(fun = mean, geom = "point", color = "black", fill = "red", shape = 21) +
  ylab("Within sample\nweighted UniFrac distance") +
  geom_vline(xintercept = 3.5,
             color = "black",
             size = 0.25) +
  ylim(c(-0.01,1.5)) +
  scale_fill_manual(values = c("blue", "steelblue1")) +
  geom_text(data = data_text_W, mapping = aes(x = x, y = y, label = wunifrac),
  size =4) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        legend.position = "none", 
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        text = element_text(size = 14),
        strip.background =element_rect(fill="white"))
```

# Create multi-paneled plot showing all distance metrics
#########################################################################################




# Create plot
```{r}
figure_tech_rep <- plot_grid(boxplot_jaccard,
                                 boxplot_rpca,
                                 boxplot_unifrac,
                                 boxplot_wunifrac,
                                 labels = c("A", "B", "C", "D"),
                                 label_size = 24,
                                 label_fontfamily = 'sans',
                                 ncol = 2,
                                 hjust = -0.25)

```

```{r}
figure_tech_rep
```
```{r}
#library(ggpubr)
#ggqqplot(tech_rep_wunifrac$value)
```


```{r}
save_plot('16S_figure_tech_rep_20x15.png',
          figure_tech_rep,
          base_width = 16,
          base_height = 9)
```

```{r}
library(ade4)
```


```{r}
head(tech_rep_jaccard, n=10)
```
```{r}
library(dplyr)
```


```{r}
jaccard_matrix_dists <- filter(tech_rep_jaccard, sample1_extraction_protocol == 'matrix')
jaccard_matrix_dists
```

```{r}
jaccard_plate_dists <- filter(tech_rep_jaccard, sample1_extraction_protocol == 'plate-based')
jaccard_plate_dists
```







