---
title: "metab_matrix_HBM_tech_reps"
output: html_document
date: "2022-10-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
setwd('/Users/cbrennan/Documents/LCMS_Matrix_Tube/jupyter_notebooks/QE_DATA')
```

```{r}
library(tidyverse)
library(cowplot)
library(ggpubr)
library(svglite)
```

```{r}
tech_rep_jaccard <- read_tsv("metab_data_tech_reps_jaccard.txt")
tech_rep_canberra <- read_tsv("metab_data_tech_reps_canberra.txt")
```

```{r}
tech_rep_jaccard$sample1_storage_solution <- factor(tech_rep_jaccard$sample1_storage_solution, levels = c("etoh", "isopropanol"))
tech_rep_canberra$sample1_storage_solution <- factor(tech_rep_canberra$sample1_storage_solution, levels = c("etoh", "isopropanol"))
```

```{r}
tech_rep_jaccard
```

```{r}
levels(tech_rep_jaccard$sample1_storage_solution) = c("etoh", "isopropanol")
levels(tech_rep_canberra$sample1_storage_solution) = c("etoh", "isopropanol")
```

# Re-order levels of the sample type variable (optional)
## Note: Change the levels to those for your variable
```{r}
tech_rep_jaccard$ATTRIBUTE_sample_type2 <- factor(tech_rep_jaccard$ATTRIBUTE_sample_type2, levels = c("human_feces", "mouse_feces", "human_saliva_before_brushing", "human_saliva_after_brushing"))
tech_rep_canberra$ATTRIBUTE_sample_type2 <- factor(tech_rep_canberra$ATTRIBUTE_sample_type2, levels = c("human_feces", "mouse_feces", "human_saliva_before_brushing", "human_saliva_after_brushing"))
```

# Re-name levels for the sample type variable (optional)
## Note: Change the levels to those for your variable
```{r}
levels(tech_rep_jaccard$ATTRIBUTE_sample_type2) <- c("human_feces", "mouse_feces", "saliva_before_brush", "saliva_after_brush")
levels(tech_rep_canberra$ATTRIBUTE_sample_type2) <- c("human_feces", "mouse_feces", "saliva_before_brush", "saliva_after_brush")

```

```{r}
tech_rep_jaccard_plate <- filter(tech_rep_jaccard,sample1_storage_solution == "etoh")
tech_rep_jaccard_matrix <- filter(tech_rep_jaccard,sample1_storage_solution == "isopropanol")
tech_rep_jaccard_plate_mouse <- filter(tech_rep_jaccard_plate,ATTRIBUTE_sample_type2 == "mouse_feces")
tech_rep_jaccard_matrix_mouse <- filter(tech_rep_jaccard_matrix,ATTRIBUTE_sample_type2 == "mouse_feces")

wilcox.test(tech_rep_jaccard_plate_mouse$value, tech_rep_jaccard_matrix_mouse$value)
```

```{r}
tech_rep_canberra_plate <- filter(tech_rep_canberra,sample1_storage_solution == "etoh")
tech_rep_canberra_matrix <- filter(tech_rep_canberra,sample1_storage_solution == "isopropanol")
tech_rep_canberra_plate_mouse <- filter(tech_rep_canberra_plate,ATTRIBUTE_sample_type2 == "mouse_feces")
tech_rep_canberra_matrix_mouse <- filter(tech_rep_canberra_matrix,ATTRIBUTE_sample_type2 == "mouse_feces")

wilcox.test(tech_rep_canberra_plate_mouse$value, tech_rep_canberra_matrix_mouse$value)
```



```{r}
tech_rep_jaccard_plate <- filter(tech_rep_jaccard,sample1_storage_solution == "etoh")
tech_rep_jaccard_matrix <- filter(tech_rep_jaccard,sample1_storage_solution == "isopropanol")
tech_rep_jaccard_plate_human <- filter(tech_rep_jaccard_plate,ATTRIBUTE_sample_type2 == "human_feces")
tech_rep_jaccard_matrix_human <- filter(tech_rep_jaccard_matrix,ATTRIBUTE_sample_type2 == "human_feces")

wilcox.test(tech_rep_jaccard_plate_human$value, tech_rep_jaccard_matrix_human$value)
```

```{r}
tech_rep_canberra_plate <- filter(tech_rep_canberra,sample1_storage_solution == "etoh")
tech_rep_canberra_matrix <- filter(tech_rep_canberra,sample1_storage_solution == "isopropanol")
tech_rep_canberra_plate_human <- filter(tech_rep_canberra_plate,ATTRIBUTE_sample_type2 == "human_feces")
tech_rep_canberra_matrix_human <- filter(tech_rep_canberra_matrix,ATTRIBUTE_sample_type2 == "human_feces")

wilcox.test(tech_rep_canberra_plate_human$value, tech_rep_canberra_matrix_human$value)
```




```{r}
tech_rep_jaccard_plate <- filter(tech_rep_jaccard,sample1_storage_solution == "etoh")
tech_rep_jaccard_matrix <- filter(tech_rep_jaccard,sample1_storage_solution == "isopropanol")
tech_rep_jaccard_plate_saliva_before <- filter(tech_rep_jaccard_plate,ATTRIBUTE_sample_type2 == "saliva_before_brush")
tech_rep_jaccard_matrix_saliva_before <- filter(tech_rep_jaccard_matrix,ATTRIBUTE_sample_type2 == "saliva_before_brush")

wilcox.test(tech_rep_jaccard_plate_saliva_before$value, tech_rep_jaccard_matrix_saliva_before$value)
```

```{r}
tech_rep_canberra_plate <- filter(tech_rep_canberra,sample1_storage_solution == "etoh")
tech_rep_canberra_matrix <- filter(tech_rep_canberra,sample1_storage_solution == "isopropanol")
tech_rep_canberra_plate_saliva_before <- filter(tech_rep_canberra_plate,ATTRIBUTE_sample_type2 == "saliva_before_brush")
tech_rep_canberra_matrix_saliva_before <- filter(tech_rep_canberra_matrix,ATTRIBUTE_sample_type2 == "saliva_before_brush")

wilcox.test(tech_rep_canberra_plate_saliva_before$value, tech_rep_canberra_matrix_saliva_before$value)
```





```{r}
tech_rep_jaccard_plate <- filter(tech_rep_jaccard,sample1_storage_solution == "etoh")
tech_rep_jaccard_matrix <- filter(tech_rep_jaccard,sample1_storage_solution == "isopropanol")
tech_rep_jaccard_plate_saliva_after <- filter(tech_rep_jaccard_plate,ATTRIBUTE_sample_type2 == "saliva_after_brush")
tech_rep_jaccard_matrix_saliva_after <- filter(tech_rep_jaccard_matrix,ATTRIBUTE_sample_type2 == "saliva_after_brush")

wilcox.test(tech_rep_jaccard_plate_saliva_after$value, tech_rep_jaccard_matrix_saliva_after$value)
```

```{r}
tech_rep_canberra_plate <- filter(tech_rep_canberra,sample1_storage_solution == "etoh")
tech_rep_canberra_matrix <- filter(tech_rep_canberra,sample1_storage_solution == "isopropanol")
tech_rep_canberra_plate_saliva_after <- filter(tech_rep_canberra_plate,ATTRIBUTE_sample_type2 == "saliva_after_brush")
tech_rep_canberra_matrix_saliva_after <- filter(tech_rep_canberra_matrix,ATTRIBUTE_sample_type2 == "saliva_after_brush")

wilcox.test(tech_rep_canberra_plate_saliva_after$value, tech_rep_canberra_matrix_saliva_after$value)
```




```{r}
data_text_W <- data.frame(jaccard = c("W=142", "W=113","W=48","W=67"), canberra = c("W=81","W=56","W=47","W=41"), unifrac = c("W=127","W=114","W=56","W=92"), wunifrac = c("W=205","W=89","W=57","W=108"),x = 1.5, y = c(1,1,1,1), ATTRIBUTE_sample_type2 =c("human_feces", "mouse_feces" ,"saliva_before_brush", "saliva_after_brush"))
data_text_W$ATTRIBUTE_sample_type2 <- factor(data_text_W$ATTRIBUTE_sample_type2, levels = c("human_feces", "mouse_feces", "saliva_before_brush", "saliva_after_brush"))
data_text_W
```


```{r}
boxplot_jaccard <- ggplot(tech_rep_jaccard, aes(x = sample1_storage_solution, y = value)) +
  facet_wrap(~ATTRIBUTE_sample_type2) +
  geom_boxplot(outlier.alpha = 0, aes(fill = sample1_storage_solution)) +
  geom_jitter(width = 0.2, size = 0.5) +
  stat_summary(fun = mean, geom = "point", color = "black", fill = "red", shape = 21) +
  stat_compare_means(method = "wilcox.test",paired = F,vjust=2, hjust=-0.2,size =4) +
  ylab("Within sample\nJaccard distance") +
  geom_vline(xintercept = 3.5,
             color = "black",
             size = 0.25) +
  ylim(c(-0.01,1.2)) +
  scale_fill_manual(values = c("blue", "steelblue1")) +
  theme_bw() +
geom_text(data = data_text_W, mapping = aes(x = x, y = 1, label = jaccard),
  size =4) +
  theme(axis.title.x = element_blank(),
        legend.position = "none", 
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        text = element_text(size = 16),
        strip.background =element_rect(fill="white"))


boxplot_canberra <- ggplot(tech_rep_canberra, aes(x = sample1_storage_solution, y = value)) +
  facet_wrap(~ATTRIBUTE_sample_type2) +
  geom_boxplot(outlier.alpha = 0, aes(fill = sample1_storage_solution)) +
  geom_jitter(width = 0.2, size = 0.5) +
  stat_summary(fun = mean, geom = "point", color = "black", fill = "red", shape = 21) +
  stat_compare_means(method = "wilcox.test",paired = F,vjust=2, hjust=-0.2,size =4) +
  ylab("Within sample\nCanberra distance") +
  geom_vline(xintercept = 3.5,
             color = "black",
             size = 0.25) +
  ylim(c(-0.01,1500)) +
  scale_fill_manual(values = c("blue", "steelblue1")) +
  theme_bw() +
geom_text(data = data_text_W, mapping = aes(x = x, y = 1300, label = canberra),
  size =4) +
  theme(axis.title.x = element_blank(),
        legend.position = "none", 
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        text = element_text(size = 16),
        strip.background =element_rect(fill="white"))


```

# Create multi-paneled plot showing all distance metrics
#########################################################################################

```{r}
tech_rep_canberra
boxplot_canberra
```




# Create plot
```{r}
figure_tech_rep <- plot_grid(boxplot_jaccard,
                                 boxplot_canberra,
                                 labels = c("A", "B"),
                                 label_size = 24,
                                 label_fontfamily = 'sans',
                                 ncol = 2,
                                 hjust = -0.25)

```

```{r}
figure_tech_rep
```
```{r}
#library(ggpubr)
#ggqqplot(tech_rep_wunifrac$value)
```


```{r}
save_plot('METAB_figure_tech_rep_20x15.png',
          figure_tech_rep,
          base_width = 16,
          base_height = 9)
```

```{r}
#library(ade4)
```














